### ISSUE TITLE
General Comments/Tracking

### ISSUE THREAD

**Issue by jessica-writes-code** [jmoore523/MSE231-Assignment4#1]
@poorna-kumar @binghailing 

Earlier today we brainstormed questions that we could ask in our survey. I think that Poorna came up with a really great idea about AI/Universal Basic Income. Below, I tried to formalize the questions that we might ask:
1) Are you familiar with artificial intelligence?
2) Do you think that advancements in artificial intelligence might threaten your job?
3) Do you think that advancements in artificial intelligence might threaten the jobs of people that you know?
4) Would you support a policy that ensures all citizens an unconditional sum of money (i.e., "Universal Basic Income")?

In the last question, we might provide a link to the wiki for "universal basic income".

Please let me know if you have edits/suggestions or if you would prefer to consider other topics. The other primary one that was suggested was about how individuals get their health insurance and how they feel about the ACA.

**Comment by jessica-writes-code** [comment]
To Do:
- [x] Determine research question
- [ ] Run a small trial/make edits as necessary
- [ ] Run a large trial (200 people)
- [ ] Analyze unadjusted data
- [ ] Generate statistically adjusted estimates for substantive questions using census data
- [ ] Identify and write about a natural experiment

**Comment by poorna-kumar** [comment]
Some relevant links (we might want to include them as references in the report -- don't waste your time clicking and reading; I'm just creating an archive here because I don't want to lose the links):
http://link.springer.com/article/10.3758/s13428-013-0365-7#page-1
http://cdp.sagepub.com/content/23/3/184.full

**Comment by jessica-writes-code** [comment]
Other ideas:

1) Health insurance. Questions to include:
a. Do you have health insurance?
b. If so, how do you acquire your health insurance? (e.g., job, state-funded system, exchange, direct-purchase, etc.)
c. How do you feel about the Affordable Care Act? (e.g., Very positive, Somewhat positive, etc.)

2) Women's health. Questions to include:
a. How do you feel about the Planned Parenthood organization?
b. Should insurance companies be required to cover birth control?
c. Should individuals have access to abortion services?

3) Climate change. Questions to include:
a. Do you believe that climate change is occurring?
b. If so, do you believe that climate change is human-caused?
c. How do you feel about President-elect Trump's proposal to quit the Paris Climate Agreement?

I literally cannot think of anything not political right now. I'm sorry about that.

**Comment by poorna-kumar** [comment]
One of my concerns about our old idea (and all of these) is that they're
basically opinion surveys: not experiments as such. No harm in doing that,
but if we could come up with an experiment to test a hypothesis that would
be more in line with what we've been learning.

**Comment by jessica-writes-code** [comment]
Ah. I figured that the hypothesis would essentially be that individuals who believe their jobs might be threatened (or that their friends' jobs might be threatened by AI) would be more inclined to support UBI.

Similarly, I think that the health insurance questions would serve to test the (related) hypotheses that people who currently use the exchanges like the ACA and, more significantly, that people who get their health insurance through their job do not like the ACA. We could even add a question about how people got their health insurance pre-ACA (e.g., in 2009) and evaluate the opinions of the people who switched.

If we want to test a hypothesis that's unrelated to people's opinions about things, I think we'll have to search a little harder. I'm having difficulty coming up with anything especially interesting off of the top of my head.

Only one major idea: If we want to go a little off-book, we can recreate one of those "James" and "Jane" tests, where you have people read a paragraph or two about someone and then answer questions about the person they read about. You randomly assign people to be reading about "James" or "Jane" but keep all the rest the same. This is an experiment that's been done plenty of times (in plenty of different contexts -- gender, race, etc.). The only "twist" on it that I could see being interesting would be randomizing people to be reading about a gay couple vs. a straight couple; within that you could even do gay men vs. gay women. Hesitations on that: 1) We might be toeing some social lines that it would be tricky to discuss in a straight-forward manner, 2) it's not exactly to the letter of the HW assignment, and 3) I have literally no idea how to randomize things w/in surveys on Amazon Mechanical Turk. (This blog discusses the latter: http://babieslearninglanguage.blogspot.com/2013/10/randomization-on-mechanical-turk_10.html)

**Comment by jessica-writes-code** [comment]
I'm sorry that you just sort of got my stream-of-conciousness ramblings...

**Comment by poorna-kumar** [comment]
I'm sorry -- I misread the assignment question. D'oh. 😌 I thought the
natural experiment was supposed to be done with Turk, but they're
unrelated. So any of the previous questions are good with me.

And the James/Jane test sounds really nice: might be a good thing to write
about for our natural experiment. There's also another idea I had, which is
to measure the effects of polls on voting patterns (it looks like a lot of
work has already been done on this topic, which reduces its sheen
somewhat).

**Comment by jessica-writes-code** [comment]
That said, we now have the opportunity to do a pretty immediate
post-election survey. So, that could be our bit of sheen.

Anyway, maybe let's briefly discuss after class and settle on one so that
we can do a test run this evening.

**Comment by jessica-writes-code** [comment]
Okay, based on our discussion earlier today, we are going to go with the AI-related survey. Below is a proposal for the questions. These are (obviously) in addition to the basic demographic questions that we are required to ask by the assignment.

1) How would you describe your political affiliation?
- Very conservative
- Somewhat conservative
- Moderate
- Somewhat liberal
- Very liberal

2) Do you think that advancements in automation and/or artificial intelligence might eliminate your job (or primary source of income)?
- Yes
- Unsure
- No

3) Would you support a policy of "Universal Basic Income" (as described below)?

"Universal Basic Income" is a form of social security in which all citizens or residents of a country regularly receive an unconditional sum of money, either from a government or some other public institution, in addition to any income received from elsewhere. The amount from the government is enough to purchase basic necessities (e.g., food, water, housing).

For additional details, please see: https://en.wikipedia.org/wiki/Basic_income
- Yes
- Unsure
- No

@poorna-kumar - Can you please either edit or approve the above? Then, @binghailing can implement the trial.

**Comment by poorna-kumar** [comment]
Hi Jessica --

Two suggestions:
1. Reduce the number of political affiliations from five to three? (Or
   maybe we should keep it at five, and then collapse it to three if we see
   fit later on).
2. Maybe specify "advancements in AI will eliminate your job in the next
   5/10/25 years"? A timeframe would be helpful for us to understand how
   immediate people perceive the threat of AI to be.

Poorna

**Comment by jessica-writes-code** [comment]
Great. Thank you, Poorna! Revised version below:

1) How would you describe your political affiliation?
- Conservative
- Moderate
- Liberal

2) Do you think that advancements in automation and/or artificial intelligence might eliminate your job in the next 15 years (or primary source of income)?
- Yes
- Unsure
- No

3) Would you support a policy of "Universal Basic Income" (as described below)?

"Universal Basic Income" is a form of social security in which all citizens or residents of a country regularly receive an unconditional sum of money, either from a government or some other public institution, in addition to any income received from elsewhere. The amount from the government is enough to purchase basic necessities (e.g., food, water, housing).

For additional details, please see: https://en.wikipedia.org/wiki/Basic_income
- Yes
- Unsure
- No

Look good to you?

**Comment by poorna-kumar** [comment]
Yes. Looks great! I'm only wondering if my suggestion of collapsing the
number of groups was a good idea. :P I guess I leave the final call on that
to you both.

One more small change: "job (or primary source of income) in the next 15
years".

Btw, thanks a lot for keeping us on track, Jessica! I'd never have started
so early, but I'm so grateful we're doing so.

**Comment by jessica-writes-code** [comment]
I think collapsing is probably a good idea. The additional layers just introduce variance without likely giving us much else to work with (since we are only surveying 200 people).

I fixed the grammatical error you found. So, final draft is below. @binghailing - Can you start the survey test run?

1) How would you describe your political affiliation?
- Conservative
- Moderate
- Liberal

2) Do you think that advancements in automation and/or artificial intelligence might eliminate your job (or primary source of income) in the next 15 years?
- Yes
- Unsure
- No

3) Would you support a policy of "Universal Basic Income" (as described below)?

"Universal Basic Income" is a form of social security in which all citizens or residents of a country regularly receive an unconditional sum of money, either from a government or some other public institution, in addition to any income received from elsewhere. The amount from the government is enough to purchase basic necessities (e.g., food, water, housing).

For additional details, please see: https://en.wikipedia.org/wiki/Basic_income
- Yes
- Unsure
- No

**Comment by poorna-kumar** [comment]
http://economicspsychologypolicy.blogspot.com/2015/06/list-of-19-natural-experiments.html
-- some more inspiration for part 2 of our HW.

**Comment by jessica-writes-code** [comment]
Hi all -

We've floated some ideas about the natural experiment that we could discuss. I wanted to get those down and add a few more. See below:

1) Bag taxes.

Some cities that border each other have different bag tax policies. We could investigate how this affects consumer spending in those cities, likelihood of shopping patterns changing after the tax is implemented, etc.

2) Redistricting and political engagement.

There seems to be some literature on how winner-take-all systems, like the Electoral College, tend to depress voter turnout, because people don't think their vote will matter. People who vote in line with the expected majority don't bother because the region will swing their way in spite of their inaction and people who vote against the expected majority don't bother because they know they'll be out-voted. (Empirically, it seems that there is higher voter turnout in battleground states: http://qcpages.qc.edu/political_science/profmat/Lipsitz_Consequences%20of%20Battleground.pdf, http://www.usatoday.com/story/news/politics/2012/12/23/voter-turnout-swing-states/1787693/)

Every 10 years (with the census), Congressional representative districts are redrawn. We could analyze whether voter participation (per capita) decreases when an area moves from a relatively competitive district to a less competitive district (or vice-versa).

3) Mariel Boatlift and xenophobia

Per the article Poorna linked, in 1980 a significant number of Cubans entered the US and took up residence in Miami. One could look at public opinions, campaign speeches, etc. to see if Miami became more or less xenophobic over the course of the next few years. This would be a differences-in-differences analysis -- we'd need to compare pre/post Mariel Boatlift Miami to pre/post Mariel Boatlift other cities. 

How do we feel about any of the above? Any other ideas?

Also, the bit about "16 and pregnant" in the article Poorna linked is hilarious.

**Comment by jessica-writes-code** [comment]
@poorna-kumar @binghailing 

Hi all -

I wrote up a draft of section 2 of part I and started writing some things for part II. I have one concern about our idea for part II. The assignment says: 

You do not need to carry out any data analysis, but the natural experiment you describe should be based on a specific instance of as-if randomization that does in fact exist in the real-world. That is, it should be possible in theory to carry out your proposal. 

However,  because California banned plastic bags in 2016, we couldn't actually currently carry out our proposal (since the natural experiment no longer exists). Do the two of you think that our idea violates his instructions or am I reading too much into the phrasing?

Jessica

**Comment by jessica-writes-code** [comment]
So, I've done slightly more thinking about the above. I think our idea is still okay. While the randomization does not currently exist, it did at one point. Given how difficult it is to find a reasonable natural experiment, I speculate that is sufficient. Moreover, we could still carry out the analysis; we'd just be relying on historical data. And, realistically, that's the case for all major papers on natural experiments -- e.g., no one was writing about the draft as an experiment at the time of the draft; all those papers were written later.

Please speak up if you disagree and think we should change the idea.

**Comment by poorna-kumar** [comment]
I agree with this.

**Comment by jessica-writes-code** [comment]
Great. Thank you, Poorna.

I started writing some stuff about it; I'm having a little difficulty figuring out if I've said what needs to be said in the methodology section. So if someone would like to take a look at that and add some stuff, it would be great. 

I also haven't done anything to the caveats section, largely because I'm having difficulty thinking about major issues. The ones that strike me initially are:
- We assume that businesses on both sides of a city/town/whatever border are affected in basically the same way. That might not be true if counties that implemented or did not implement bag bans/taxes also did other things at the same time.
- The as-if random assumption is probably not a terrible one at a border, but is questionable elsewhere, since counties/cities that implemented bag bans/taxes are probably more well-off than others. So, the distance from the border that we consider is important; we could get into trouble if we consider businesses that are too far from it.

However, both of those seem pretty obvious, so I'm searching for something more...

**Comment by poorna-kumar** [comment]
Thanks for your note, Jessica. I looked at the document, and what's been written so far is great. That said, I think we can add a few things to the document:

1. We should probably define exactly what is our response variable. I propose average (median?) daily sales in dollars, but this is pretty arbitrary and I haven't thought it through. Please suggest alternative response variables if this seems flawed. 

2. To build off point 1, suppose we look at two adjacent areas, one with a bag ban (Area 1) and one without (Area 2). Then, we should be able to identify businesses of interest in each area and put them into categories (small/medium/large and/or grocery/pharmacy/clothing/etc.). After that, for each store we have, we look at the change in sales before and after the treatment began, i.e., we compute, for store i, we compute metric(i) = average_daily_sales_before(i) - average_daily_sales_after(i). We need to define how to compute this average: I assume we will identify a period of interest (how long?) and take the average across that period. Then, we can compute this metric for every store i, and find the average value of this metric in each category j of store in Area 1 and Area 2. So, for each category j of store, we can find the difference in this metric between Area 1 and Area 2, and test whether this is significantly different from zero. 

- How do we generalize this to many areas? One way is to find this difference in avg metric of store category j (say, d_j_area12, for the difference between areas 1 and 2) for adjacent areas. We can compute this for every pair of adjacent areas we care about, and then test whether the average value is greater than/less than zero. (Can one area be adjacent to two other areas? How does this affect the statistics of our problem? Might be easier to sidestep this issue altogether, and say that a single city/area can only be looked at once in our problem). My knowledge of applied statistics is poorer than yours, so please feel free to shoot this down. 

3. We could write a little bit about how we bucket businesses -- do we want to bucket them based on products (grocery stores, pharmacies, clothing, etc.) or size (small, medium, large) or both? The more groups we have, the less data we have per group, but the more we are controlling for.

I've edited the document a little bit, and will edit it some more in the next hour or so. I've also left some comments in the document. I guess this is one of those assignments where the more we think about our problem, the more choices we realize we could make, and the more choices we make, the more caveats and limitations we impose. :P

**Comment by poorna-kumar** [comment]
I got a lot of ideas from reading the beginning of the Card paper, but I haven't finished reading it. I'll go over it a bit more tonight and make some more changes.

**Comment by jessica-writes-code** [comment]
Thanks so much for your reply, Poorna! On the issues that you pointed out:

1/2. I agree. I think defining a metric is important and I think "average daily profit" is appropriate. (See response to your first comment in the document for the justification for "profit" over "sales" or "revenue", though ultimately not a huge deal.)

Also, agreed with the computation. As far as time-horizon, I suggest computing the avg_daily_profit_before as sales during the 4-week period that end a month before the bag ban and then avg_daily_profit_after as sales during the 4-week period that begins a month after the bag ban.  (I recognize that is a bit difficult to phrase...) This addresses a few issues:
- reactions to the change: people might start preparing for the bag ban, when they know it's coming. I'm not sure if/how that would affect sales, but it's probably smart to avoid capturing data during the time period because of it. More significantly, for some time period after the ban, people either might not be aware of it or might not have adjusted to it (e.g., they forget, and go shopping when they otherwise wouldn't). The month delay before we start sales calculations means we don't erroneously capture those effects.
- intra-week flux in profit: if we choose a timespan defined by a month or period of days, we stand some risk of capturing more weekends (or whatever constitutes a high-spending day) in the before time period than the after time period (or vice versa). This would artificially bias our results.

I also agree with your assessment of how to generalize the method. Calculating for every pair of areas seems like the most effective procedure. Should there be places (and likely, there are) in which a treated area is next to two un-treated areas, I would agree that we not use those areas in our analysis. They add needless complication.

3. Excellent. Thank you! I've added a bit about the bucketing. I've suggested grocery, pharmacy, and department stores, as these seem most likely to be impacted. I've also suggested division into small, medium, and large. I suspect that if we look at the entirety of LA County, we should not have a huge problem with not having enough data. (Though, I don't really know the area, so maybe @binghailing can comment?)

Generally, I've responded to your comments in the document and added a few of my own. LMK if I've missed any.

**Comment by poorna-kumar** [comment]
I've added a bit more to the document, and listed some caveats as comments. 

I think we're at a good length for methodology/caveats now (although of course it might need to be edited and/or cut down a bit). Maybe we should add a bit more about the social science question we're asking (for example, why it's interesting, theories for what could happen to businesses after a bag ban, etc.).

**Comment by poorna-kumar** [comment]
I was just thinking about our idea, and I realized, if we focus on areas
just near the border, won't we be giving customers the option to go to
another store across the border, which doesn't have the bag ban?

So we are not really measuring the impact of the bag ban on businesses, but
instead the impact of a piecemeal bag ban on businesses which are close to
competing establishments which do not have the ban. I wonder if this
changes things a lot.

**Comment by jessica-writes-code** [comment]
So, I'd had the same thought. And, I agree that we're not necessarily going
to capture the same effect as if bags were banned in their entirety. We
should certainly include this issue in the caveats section.

I do still think that the information we are capturing is important. It
certainly answers questions about consumer behavior changes in response to
the bag ban. If we see non-bag-ban stores have revenue increases that are
roughly proportional to the profit decreases in bag-ban stores, we can say
that consumers do respond. And they respond in ways that hurt stores
subject to the bag ban. The social science implication is then that, when
implementing a bag ban, it needs to be done in a large-scale way, to
prevent disadvantaging the businesses that happen to be subject to it. So,
that isn't exactly "bag-ban is good" or "bag-ban is bad", but it does have
serious policy implications.

Also, if we want to just test the expense issue, maybe we could suggest
capturing expense as a proportion of revenue? That would tell us if bag-ban
businesses have their expenses per sale go up vs. non bag-ban businesses.

Does the above seem logical?

**Comment by jessica-writes-code** [comment]
Also, I think we might be able to reasonably make the assumption that the bag ban is annoying to consumers, but really only has effects at the margin -- i.e., they choose to walk into a store to pick up something small or not. I don't think that it would be so impactful as to cause them to drive out of their way to go shopping elsewhere (the gas costs would off-set the gain from not paying for bags).

**Comment by poorna-kumar** [comment]
Thanks, Jessica. You're right that we are still asking an important question -- if we do see a change in profit before and after the ban for stores that are affected by the ban, we can conclude that either consumers are going elsewhere, or it just organically hurts business profits because customers don't like it: either is a significant outcome. 

I am not sure if there is any way to tell whether a store's profits fell because: a. customers were put off by the bag ban and just shopped less, or b. whether customers moved to a competing establishment because they could. So I'm not sure how to disentangle these two conclusions, and draw a single policy conclusion from it. For example, what if customers shopped less overall (because the bag ban was an inconvenience), but also chose to shop a larger percent of the time at establishments without the ban? If we are comparing two establishments that are very close, wouldn't it be very easy for a customer in a car to choose which one to go to? If it's just a few hundred meters of distance, the gas charges would be quite low too, right? I guess in the absence of tracking information for individual customers, we can't really say which of the two happened.

I had a look at the Card paper again, and they had recorded that food prices in NJ increased after the increase in minimum wage. So there was an incentive for customers to eat in Pennsylvania rather than in NJ, and it's possible in theory that employment in NJ could have fallen as a result of customers' eating elsewhere and establishments having to downsize in response. However, since they recorded that employment didn't decrease, this was not an important effect to consider, as it wouldn't have changed their conclusion (admittedly, I didn't read the paper till the end). 

I suppose we can say that we'd do the same as them: ignore this fact if we find that profits don't decrease. But if they do, then we can say that one of two things occurred.

**Comment by jessica-writes-code** [comment]
Okay. Having thought about this for another 15 minutes...

My suggestion: We change our metric to be expenses divided by revenue (i.e., expenses per sale) and compare that between stores on each side of the border. This answers the question of whether a business's expenses go up nontrivially, which is an interesting social science question about the implementation of bag bans, more generally (not just in implementation). It also controls for the issue of sales movement across the border, because it's a ratio, rather than a total quantity of sales.

Alternatively, we can do as you suggest. That method is just a bit harder to explain, is all.

**Comment by poorna-kumar** [comment]
I'm not sure what expenses as a proportion of revenue would capture: I would expect it would change in fairly predictable ways with a bag tax, right? (More expenses per sale because the store pays a tax on the bag it sold, and more revenue per sale because the customer pays for the bag too?) And ultimately, it's not a good measure of robustness of business -- even if a store had low expenses to revenue per sale, it could still be doing very badly because of fewer transactions. 

My inclination is to go with what we had earlier. I was heartened by the fact that the Card paper also basically ignored this effect. We could include this in the caveats and limitations section.

**Comment by jessica-writes-code** [comment]
Alrighty. Sounds good to me.

**Comment by poorna-kumar** [comment]
Silly question: could you point me to a source that describes the plastic bag ban and tax in LA? When I searched, I could only seem to find a plastic bag ban, along with a ten-cent fee on paper bags.

**Comment by jessica-writes-code** [comment]
Hi Poorna, I don't think I quite understand the question.

I agree that LA only implemented a plastic bag ban & 10-cent fee on paper bags. Before that, I believe, a number of areas scattered throughout LA county had their own bag bans/taxes. I thought we were studying the latter. I actually had difficulty finding anything that discussed those taxes, specifically, but I'd gotten that understanding from @binghailing . However, we can certainly remove the discussion of taxes, since that will likely make the entire write-up cleaner.

**Comment by poorna-kumar** [comment]
Hmm, so what I could find said that there were a lot of regions in LA that
had implemented a bag ban plus fee for paper bags. I couldn't find anything
about another tax. I guess we can just talk about one treatment and one
control then. (In fact, it would make our write-up simpler, which would be
good).

**Comment by jessica-writes-code** [comment]
Yeah. And having to say "bag ban and/or tax" every time was getting tedious.

Just discussing the ban/fee sounds good to me

**Comment by poorna-kumar** [comment]
Discovered today: an interesting regression discontinuity at http://voxeu.org/article/cheaper-flights-and-scientific-collaboration.

**Comment by jessica-writes-code** [comment]
Nifty. Thanks for sharing!

**Comment by jessica-writes-code** [comment]
I've done some more editing to the report. Specifically, ...
- I added some stuff about the policy-relevance of the study
- I tried to remove the discussion of bag taxes, so that we indicate we are only interested in bag bans as a treatment effect.
- I tried to write-up the caveats section. I'm sure there's more to add, so please feel free to change, as necessary.

Also, I left a few comments regarding sentences that I commented-out.

**Comment by jessica-writes-code** [comment]
@poorna-kumar @binghailing 

Hi all -

I noticed this morning that Part I had still not been written. I've filled it out, so that it is now at least in a submittable form (i.e., no notes, etc.). Please feel free to revise or rewrite, but I wanted to make sure we had something that we could turn in this evening.

Jessica

**Comment by poorna-kumar** [comment]
Hi Jessica,

Sorry about that! I didn't end up having the energy to do it last night (my
bad), so I was planning to get to it today morning. It looks like you've
done a very good job on it -- I'm reading through it and trying to identify
what I can add to it. It should be in submittable form by class time today.

Poorna
